#Import Libraries

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np

#Importing Dataset

In [3]:
filepath = "/content/drive/MyDrive/Colab Notebooks/SYLHET_data.csv"
df = pd.read_csv(filepath)
dataset = pd.read_csv(filepath)
x = dataset.iloc[ : , 1:20].values
y = dataset.iloc[:,-1].values
dataset.head(3)

datetime  tempmax  tempmin  temp  feelslikemax  feelslikemin  feelslike  \
0  15-08-14     30.9     25.7  27.4          40.9          25.7       30.6   
1  16-08-14     30.9     25.4  27.5          39.2          25.4       30.8   
2  17-08-14     32.5     25.2  28.0          41.9          25.2       32.1   

    dew  humidity  precip  ...  windspeed  winddir  sealevelpressure  \
0  26.1      93.0    24.8  ...       24.1    175.6            1003.9   
1  25.8      90.5    30.5  ...       25.9    176.5            1004.4   
2  25.9      89.0     9.5  ...       15.1    199.4            1004.1   

   cloudcover  visibility  solarradiation  solarenergy  uvindex  Rain_today  \
0        96.0         3.7           184.7         15.8        6        rain   
1        92.9         3.8           208.1         17.8        8        rain   
2        92.9         3.3           255.9         22.0        9        rain   

  Rain_tomorrow  
0          rain  
1          rain  
2          rain  

[3 rows x 21 columns]

In [4]:
dataset.corr()

<ipython-input-4-c187c74d1e71>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataset.corr()


tempmax   tempmin      temp  feelslikemax  feelslikemin  \
tempmax           1.000000  0.972557  0.994132      0.982160      0.971342   
tempmin           0.972557  1.000000  0.989831      0.987343      0.999646   
temp              0.994132  0.989831  1.000000      0.992436      0.988925   
feelslikemax      0.982160  0.987343  0.992436      1.000000      0.986966   
feelslikemin      0.971342  0.999646  0.988925      0.986966      1.000000   
feelslike         0.980828  0.992870  0.994352      0.997351      0.992747   
dew               0.971790  0.991446  0.989453      0.989017      0.990761   
humidity          0.181655  0.324012  0.256019      0.294200      0.324702   
precip           -0.335353 -0.278307 -0.306709     -0.288253     -0.277394   
precipcover      -0.104201 -0.015193 -0.063001     -0.028237     -0.013733   
windspeed        -0.407207 -0.367524 -0.392331     -0.368618     -0.366595   
winddir           0.117922  0.142346  0.133786      0.156908      0.143114   
sealevelpressure -0.089380 -0.235399 -0.161846     -0.238410     -0.240292   
cloudcover        0.024059  0.182539  0.103233      0.153660      0.184772   
visibility       -0.508346 -0.496870 -0.511493     -0.503519     -0.495317   
solarradiation    0.004148 -0.041637 -0.017754      0.013984     -0.041258   
solarenergy       0.004993 -0.040767 -0.016873      0.014807     -0.040386   
uvindex          -0.054968 -0.120416 -0.088548     -0.068098     -0.120516   

                  feelslike       dew  humidity    precip  precipcover  \
tempmax            0.980828  0.971790  0.181655 -0.335353    -0.104201   
tempmin            0.992870  0.991446  0.324012 -0.278307    -0.015193   
temp               0.994352  0.989453  0.256019 -0.306709    -0.063001   
feelslikemax       0.997351  0.989017  0.294200 -0.288253    -0.028237   
feelslikemin       0.992747  0.990761  0.324702 -0.277394    -0.013733   
feelslike          1.000000  0.991936  0.300457 -0.286303    -0.024124   
dew                0.991936  1.000000  0.387847 -0.262568    -0.012059   
humidity           0.300457  0.387847  1.000000  0.273337     0.357458   
precip            -0.286303 -0.262568  0.273337  1.000000     0.391503   
precipcover       -0.024124 -0.012059  0.357458  0.391503     1.000000   
windspeed         -0.373898 -0.377408 -0.036955  0.291026     0.209363   
winddir            0.156952  0.142315  0.099809 -0.006052     0.129752   
sealevelpressure  -0.241884 -0.230470 -0.496403 -0.282539    -0.378008   
cloudcover         0.167093  0.191219  0.618026  0.327268     0.390290   
visibility        -0.503795 -0.530799 -0.366806  0.110892    -0.066621   
solarradiation    -0.005896 -0.068794 -0.376194 -0.123739    -0.037705   
solarenergy       -0.005011 -0.067894 -0.375633 -0.123650    -0.038095   
uvindex           -0.088640 -0.145622 -0.431533 -0.134266    -0.109075   

                  windspeed   winddir  sealevelpressure  cloudcover  \
tempmax           -0.407207  0.117922         -0.089380    0.024059   
tempmin           -0.367524  0.142346         -0.235399    0.182539   
temp              -0.392331  0.133786         -0.161846    0.103233   
feelslikemax      -0.368618  0.156908         -0.238410    0.153660   
feelslikemin      -0.366595  0.143114         -0.240292    0.184772   
feelslike         -0.373898  0.156952         -0.241884    0.167093   
dew               -0.377408  0.142315         -0.230470    0.191219   
humidity          -0.036955  0.099809         -0.496403    0.618026   
precip             0.291026 -0.006052         -0.282539    0.327268   
precipcover        0.209363  0.129752         -0.378008    0.390290   
windspeed          1.000000 -0.000825         -0.216160    0.159882   
winddir           -0.000825  1.000000         -0.201420    0.111685   
sealevelpressure  -0.216160 -0.201420          1.000000   -0.678535   
cloudcover         0.159882  0.111685         -0.678535    1.000000   
visibility         0.248501 -0.272351         -0.031683   -0.040

In [5]:
print(x)

[[30.9 25.7 27.4 ... 15.8 6 'rain']
 [30.9 25.4 27.5 ... 17.8 8 'rain']
 [32.5 25.2 28.0 ... 22.0 9 'rain']
 ...
 [33.2 26.1 29.5 ... 20.0 7 'rain']
 [34.5 26.3 29.6 ... 24.6 9 'rain']
 [33.0 25.8 28.6 ... 24.3 8 'rain']]


In [6]:
print(y)

['rain' 'rain' 'rain' ... 'rain' 'rain' nan]


In [7]:
y = y.reshape(-1,1) # convert 1D arry to 2D array

In [8]:
print(y)

[['rain']
 ['rain']
 ['rain']
 ...
 ['rain']
 ['rain']
 [nan]]


#Taking Care of Missing Values

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
x = imputer.fit_transform(x)
y = imputer.fit_transform(y)

In [10]:
print(x)

[[30.9 25.7 27.4 ... 15.8 6 'rain']
 [30.9 25.4 27.5 ... 17.8 8 'rain']
 [32.5 25.2 28.0 ... 22.0 9 'rain']
 ...
 [33.2 26.1 29.5 ... 20.0 7 'rain']
 [34.5 26.3 29.6 ... 24.6 9 'rain']
 [33.0 25.8 28.6 ... 24.3 8 'rain']]


In [11]:
print(y)

[['rain']
 ['rain']
 ['rain']
 ...
 ['rain']
 ['rain']
 ['rain']]


#Encoding the Dataset

In [12]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
x[:,10] = le1.fit_transform(x[:,10])
le2 = LabelEncoder()
x[:,-1] = le2.fit_transform(x[:,-1])
le3 = LabelEncoder()
y = le3.fit_transform(y)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [13]:
print(x)

[[30.9 25.7 27.4 ... 15.8 6 2]
 [30.9 25.4 27.5 ... 17.8 8 2]
 [32.5 25.2 28.0 ... 22.0 9 2]
 ...
 [33.2 26.1 29.5 ... 20.0 7 2]
 [34.5 26.3 29.6 ... 24.6 9 2]
 [33.0 25.8 28.6 ... 24.3 8 2]]


In [14]:
print(y)

[2 2 2 ... 2 2 2]


#Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [16]:
print(x)

[[-0.94136012 -0.62592395 -0.82986334 ... -0.38960557 -0.71044836
   0.70726827]
 [-0.94136012 -0.63786496 -0.82608809 ...  0.02344205  0.46422154
   0.70726827]
 [-0.88457172 -0.64582563 -0.80721188 ...  0.89084207  1.05155649
   0.70726827]
 ...
 [-0.8597268  -0.61000261 -0.75058322 ...  0.47779444 -0.12311341
   0.70726827]
 [-0.81358622 -0.60204193 -0.74680798 ...  1.42780398  1.05155649
   0.70726827]
 [-0.86682535 -0.62194362 -0.78456041 ...  1.36584683  0.46422154
   0.70726827]]


#Splitting Dataset into Training set and Test set

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [18]:
print(x_train)

[[ 1.06752944  0.58011799  0.9369507  ...  1.11801826  1.05155649
   0.70726827]
 [-0.91651519 -0.64980597 -0.78833566 ... -0.94721986 -1.29778331
   0.70726827]
 [ 1.09237436  1.30055889  1.14836435 ...  1.26258493  1.05155649
   0.70726827]
 ...
 [ 0.96460047  0.13830065  0.68778462 ...  0.95279921  1.05155649
  -1.71817859]
 [-1.00879634 -0.91648851 -0.92046919 ... -1.31896272 -1.29778331
   0.70726827]
 [-1.10817603 -1.40208956 -1.23003917 ...  0.53975159  1.05155649
   0.70726827]]


In [19]:
print(y_train)

[2 2 2 ... 0 2 2]


#Training Model

In [20]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=150, random_state=0)
classifier.fit(x_train, y_train)

RandomForestClassifier(n_estimators=150, random_state=0)

In [21]:
classifier.score(x_train,y_train)

1.0

In [22]:
y_pred = le3.inverse_transform(np.array(classifier.predict(x_test),dtype=int))
y_test = le3.inverse_transform(np.array(y_test,dtype=int))

In [23]:
# print(y_pred)

In [24]:
# print(y_test)

In [25]:
y_pred = y_pred.reshape(-1,1)
y_test = y_test.reshape(-1,1)
# print(y_pred)

In [26]:
# print(x_test)

In [27]:
df = np.concatenate((y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Rain on Tommorrow','Predition of Rain'])
print(dataframe)

    Rain on Tommorrow Predition of Rain
0                rain              rain
1           clear-day         clear-day
2                rain              rain
3           clear-day         clear-day
4                rain              rain
..                ...               ...
653         clear-day         clear-day
654              rain              rain
655              rain              rain
656              rain              rain
657         clear-day         clear-day

[658 rows x 2 columns]


In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8069908814589666

#Visualizing the Results

In [29]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

[[108  28   8]
 [ 40  43  19]
 [ 21  11 380]]


In [30]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.81


In [31]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

   clear-day       0.64      0.75      0.69       144
      cloudy       0.52      0.42      0.47       102
        rain       0.93      0.92      0.93       412

    accuracy                           0.81       658
   macro avg       0.70      0.70      0.70       658
weighted avg       0.81      0.81      0.80       658

